### ISSUE TITLE
App theme should match the device's default theme

### ISSUE THREAD

**Issue by akshay8551** [bithyve/bitcoin-tribe#424]
The app should automatically adjust its theme (light or dark) based on the device's default theme settings. If the device is set to light mode, the app should switch to light mode. If the device is set to dark mode, the app should switch to dark mode. This happen until user select from App. If user select/toggle from app theme after that app's theme should be control by app.

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/78f1085d-8f25-49ad-9c02-3d4c604bae10

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/9a7bc8d9-65ce-4080-87cb-58529dd31d8d

**Comment by akshay8551** [comment]
As per discussion, Only at first time system theme apply in app. After that user's choice or if user select/toggle from app then app theme applied in app.








https://github.com/user-attachments/assets/809422b5-4f1f-4bf2-bf17-625da162cf90

**Comment by Deveshshankar** [comment]
I can see this resolved earlier by default it was dark
