### ISSUE TITLE
Animation with message 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#436]
- [x] Need to finalise and implement one of the three animation options 

- [x]  For displaying messages during processing time while creating asset

**Comment by akshay8551** [comment]
@Jddesigner0003, Could u please share illustration's json file?


<img width="1066" alt="Screenshot 2024-11-28 at 11 19 27 AM" src="https://github.com/user-attachments/assets/213e60a1-a693-4827-a67c-596587a4b8fa">


Ref - https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=3290-46384&node-type=frame&t=aKBOjFMsXmNY6e7E-0

**Comment by Jddesigner0003** [comment]
@akshay8551  can you please check and let me know if any missing JASON file 
[animation loading time (2).zip](https://github.com/user-attachments/files/17943319/animation.loading.time.2.zip)

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/85b5e9dc-bc9f-407a-bfe9-825574859ee4

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/1bb34a48-8e36-4fbc-a3d6-8df406840697

**Comment by akshay8551** [comment]
Send BTC - 



https://github.com/user-attachments/assets/c19916c5-d939-4e9a-a03b-3c85c5f79eba

**Comment by akshay8551** [comment]
Recover - 



https://github.com/user-attachments/assets/e3a052b5-572b-450b-ad4e-701dc441c722

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/e64813b2-ab7f-4d39-98c9-17f94a8d788e

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/7b78893f-6e38-45eb-a389-037095370668

**Comment by Jddesigner0003** [comment]
@akshay8551   Please check the "Issuing Asset" screen animation JASON file 

[Coin Stack.json](https://github.com/user-attachments/files/17962618/Coin.Stack.json)

**Comment by akshay8551** [comment]
Done - 







https://github.com/user-attachments/assets/e11f6886-05c4-4ef6-a0c6-6e8d8917976b

**Comment by Deveshshankar** [comment]
Completed this is an umbrella issue
