### ISSUE TITLE
Issuing collectibles in Android is time taking 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#523]
- [x] It took more than a minutes but after that also was unable to issue asset loader keeps running 

![screenshot_2024-11-12-15-44-38-43_3df711a74d68a40f5af6dea70d79c777_720](https://github.com/user-attachments/assets/b4092f14-d042-49c2-bfa8-97e4471f2797)

**Comment by akshay8551** [comment]
This issue occurred because of not handle/catch error. Right now i have catch error and show in toast..


https://github.com/user-attachments/assets/041ea237-08dd-4bbc-941b-a56914d577a6

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/c948a077-e4fe-48d2-a232-73c33e4054cc

**Comment by akshay8551** [comment]
Done - 




https://github.com/user-attachments/assets/a93a021a-df24-497f-aba1-1f0df19686ee

**Comment by Deveshshankar** [comment]
Completed
