### ISSUE TITLE
Need some info in options in creating channels (Channel management )

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#535]
- [ ] @akshay8551 Please update Channel management as per new design 

![screenshot_2024-11-13_at_4 57 30___pm_720](https://github.com/user-attachments/assets/800412e3-0bfb-4590-aac7-47e1d023d183)

**Comment by Jddesigner0003** [comment]
@Deveshshankar   Please check updated final flow 

Figma: https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=4363-12637&t=wDYrZ0Zpbxvs8owD-1

![image](https://github.com/user-attachments/assets/1e676467-352d-4895-9645-e2181192ebf8)

**Comment by Deveshshankar** [comment]
@akshay8551 You can proceed refer to latest design

**Comment by akshay8551** [comment]
![simulator_screenshot_ABB36F60-0D90-4941-8523-EFFAACD5DEA6](https://github.com/user-attachments/assets/b408a8dc-3509-47c9-97b9-b2abe953d316)

**Comment by akshay8551** [comment]
![simulator_screenshot_EC810171-82E4-49E6-BF22-9662475CDCBD](https://github.com/user-attachments/assets/6044728b-bc02-4496-a181-982bc1d6ae72)

![simulator_screenshot_A27AF03B-6CC6-4974-A829-8C1E01D1E8B8](https://github.com/user-attachments/assets/67d03b9c-0f80-446b-9fe8-ddb7e213799e)


![simulator_screenshot_320D9D51-87B7-4520-B388-1780C6694771](https://github.com/user-attachments/assets/771bb851-786c-472a-a5ec-83623aebea91)

**Comment by akshay8551** [comment]
Channel Creation after changes - 


https://github.com/user-attachments/assets/1909ffbf-92b4-4a22-b2cf-01cdde018bdb

**Comment by akshay8551** [comment]
According to new UX 
-- CC @Deveshshankar 

![simulator_screenshot_47B42ED2-CF03-4496-94DD-52DA43FAF1C5](https://github.com/user-attachments/assets/4aee3da8-a79f-4bd4-9a0d-e5c19f09d577)



![simulator_screenshot_038A8E80-D354-42FB-BE3F-3CCA5AFB14AC](https://github.com/user-attachments/assets/c172903f-b7e3-481a-b2d9-93f9bf36baba)

**Comment by Deveshshankar** [comment]
Completed
