### ISSUE TITLE
Usability issue 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#538]
if we look at the below video in first option if user clicks done keypad is getting hidden but when same task in performed at 2nd option it works as an space 
https://github.com/user-attachments/assets/b21cbe35-be79-4c1a-9275-fa75e41bd570

**Comment by akshay8551** [comment]
@Deveshshankar , As we discussed, Current implementation is fine for now. So I'm going to mark it fix.

Thanks

**Comment by Deveshshankar** [comment]
Completed
