### ISSUE TITLE
Need to change icon of this 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#543]
- [ ] Will need some other icons in settled 
- [ ] 2nd task in bottom Cc @Jddesigner0003 
<img width="322" alt="Screenshot 2024-11-14 at 5 59 12 PM" src="https://github.com/user-attachments/assets/188ddf61-256d-40a8-99ac-bf05c33430fe">

**Comment by Jddesigner0003** [comment]
@Deveshshankar   Duplicate issue so we are closing https://github.com/bithyve/bitcoin-tribe/issues/563
