### ISSUE TITLE
The extra spacing on transactions before manually refreshing

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#548]
- [ ] The extra spacing on transactions before manually refreshing

https://github.com/user-attachments/assets/c8fc32d2-e8d5-4372-8089-9c697b650f3b

**Comment by akshay8551** [comment]
For resolve this issue, I have handle both loading list and pull-to-refresh functionality outside the flatlist. So from now firstly show loader, after completing loading list and pull-to-refresh process then show list of transactions.

**Comment by Deveshshankar** [comment]
Closing resolved
