### ISSUE TITLE
Design changes (Channel Management )

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#551]
- [ ] We need to divide this in  Inbound and Outbound with different colour 

<img width="276" alt="Screenshot 2024-11-13 at 5 00 21 PM" src="https://github.com/user-attachments/assets/044fb879-8b4a-414e-83f3-d2daf3cb9249">

**Comment by Jddesigner0003** [comment]
@Deveshshankar   i think is also duplicate issue we can make only one issue for channel management for design and other things

**Comment by Deveshshankar** [comment]
@cakesoft-shashank Design is done please proceed

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/9d77f1db-2fe5-4db6-bf4d-a7077585f491

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/ce22cc37-14ba-4589-b659-ce4653b4c7e6

**Comment by Deveshshankar** [comment]
Completed it was an umbrella issue
