### ISSUE TITLE
Rethink on Wallet/Asset  details screen 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#552]
- [ ] We need to rethink about top section which is taking more space instead if we let transaction list more data it will be better 

<img width="315" alt="Screenshot 2024-11-13 at 5 01 27 PM" src="https://github.com/user-attachments/assets/f918cdac-4064-4d75-9356-f0dce2b9d718">

**Comment by Jddesigner0003** [comment]
this issue is i think duplicate so i would suggest we can merge it @Deveshshankar 

the updated wallet screen please check 

![image](https://github.com/user-attachments/assets/764acfdd-56f5-4fd5-8698-a8386fa0fa3f)

**Comment by Jddesigner0003** [comment]
@Deveshshankar  duplicate issue please close it https://github.com/bithyve/bitcoin-tribe/issues/563
