### ISSUE TITLE
We should have some option to select Created Asset ID / Asset

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#556]
- [ ] User can directly select created asset rather than going home page opening asset metadata and selecting asset id and pasting 

<img width="230" alt="Screenshot 2024-11-13 at 4 56 27 PM" src="https://github.com/user-attachments/assets/8f6b486b-3ad5-42b4-9299-55bbea021d11">

**Comment by Jddesigner0003** [comment]
@Deveshshankar  In the updated flow, the user can view their available balance in the same field. Additionally, the user can select an asset from a dropdown menu.


![image](https://github.com/user-attachments/assets/e123113d-3297-49b1-9470-4d79539b75a1)

**Comment by Jddesigner0003** [comment]
@Deveshshankar   Updated and final flow from my side i resolve all the comment on this steps now you can move this issue for development 

Figma: https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=4363-12637&t=wDYrZ0Zpbxvs8owD-1
![image](https://github.com/user-attachments/assets/1f259ec3-234e-49ab-84d5-42a85a2624bf)

**Comment by Deveshshankar** [comment]
@akshay8551 You can proceed design is ready

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/2324ec24-d430-4020-9ba0-e7a40dabb911
















https://github.com/user-attachments/assets/56ae16a6-80ae-4569-b166-939aa57ee2e6

**Comment by Deveshshankar** [comment]
Completed
