### ISSUE TITLE
Channel Details screen

### ISSUE THREAD

**Issue by akshay8551** [bithyve/bitcoin-tribe#561]
Need channel details screen's UX .

![simulator_screenshot_ACA2A3B3-A792-416D-B2AA-0ABA10A85F6A](https://github.com/user-attachments/assets/6250a2c1-90d8-4d7f-bc9c-7b7ced0d6c80)

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/63eedd70-2d1d-4748-ba25-c494f0bb96ee

**Comment by Deveshshankar** [comment]
Completed
