### ISSUE TITLE
Need content for loader at all places 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#562]
- [ ] Currently just the loader is running if we introduce some text it will be very useful for user ![IMG_057B9593A2B9-1](https://github.com/user-attachments/assets/7e6dfe0d-43b1-4127-91b3-00a8cd0367cf)

**Comment by Jddesigner0003** [comment]
@Deveshshankar   For normal refresh i dont think so we need to add there any contant and for channel creation we can design new animation with content

**Comment by Deveshshankar** [comment]
https://github.com/bithyve/bitcoin-tribe/issues/599 Closing duplicate
