### ISSUE TITLE
Will need instruction on how to create a channel (something like learn more)

### ISSUE THREAD

**Issue by cakesoft-utkarsh** [bithyve/bitcoin-tribe#565]
Will need instruction on how to create a channel (something like learn more)

- [x] I was not able to create a channel with the node I have created on Thunderstack (Tribe QA) peer url was not visible will need to add instruction screen how to create Channel
- [x] @Jddesigner0003 We will need  instruction screen for creating channels .....this is mostly educating user about the features before they start using. 
- [x] Use temporary content it will be modified by @cakesoft-shashank Will give final approval

**Comment by Jddesigner0003** [comment]
@Deveshshankar   Hey 
Based on the our 26 Nov discussion i did all the changes and this is final updated channel management flow from my side, please check it and let me know if you need any change.

Note: For Guide screen i need contant and based on contant i will find graphic for that.

Figma Link: https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=4365-14412&t=O0rFWRqrraW7bmr2-1

https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=4365-14412&t=O0rFWRqrraW7bmr2-1

**Comment by cakesoft-shashank** [comment]
Do we need this? We have enough information about fields required to open channel

**Comment by Deveshshankar** [comment]
Completed
