### ISSUE TITLE
Website (Button to be added for stores )

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#577]
- [ ] @Jddesigner0003 We need to keep icons here for play store and App Store 
- [ ] Instead of get app we can show play store and App Store icons

<img width="556" alt="Screenshot 2024-11-28 at 7 26 19 PM" src="https://github.com/user-attachments/assets/df2344d5-9b04-4a11-9363-fa8cb89655cf">

- [ ] Something like this 

 <img width="500" alt="Screenshot 2024-11-28 at 7 31 20 PM" src="https://github.com/user-attachments/assets/ece27095-4434-4d06-b594-4d66c2e4c137">

2a01-3f68-437c-b3e1-5e4c507d5ac3">

**Comment by Deveshshankar** [comment]
@Jddesigner0003 Currently we have like this <img width="680" alt="Screenshot 2024-11-28 at 7 27 51 PM" src="https://github.com/user-attachments/assets/b54d5c57-2b3d-4b7f-a575-377555a65082">

**Comment by Jddesigner0003** [comment]
@Deveshshankar  Please check both icon attached you can use SVG or PNG whatever you like 


![play store](https://github.com/user-attachments/assets/7f889c45-b2ae-432c-a298-52d77b1b799f)
![app store](https://github.com/user-attachments/assets/b0b14956-86c1-44e3-8ffd-371da18d6f04)
![play store](https://github.com/user-attachments/assets/98a14ad3-3c5a-439b-b95f-faddfa9bfc45)
![app store](https://github.com/user-attachments/assets/5b517b35-6eb5-4d6d-9f8c-649f37325020)

**Comment by Deveshshankar** [comment]
Completed 
<img width="1300" alt="Screenshot 2024-11-29 at 4 30 54 PM" src="https://github.com/user-attachments/assets/043a687f-54d8-4fb3-aecf-95bd388b9604">
