### ISSUE TITLE
Onboarding screen should be similar to Keeper 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#580]
@akshay8551 We can refer onboarding screen from Keeper

**Comment by akshay8551** [comment]
iPhone 16 Pro max -



https://github.com/user-attachments/assets/5d446850-882f-4785-846a-58fa62aa5224

**Comment by akshay8551** [comment]
iPhone SE -




https://github.com/user-attachments/assets/293705c1-aaa1-4b2c-b226-b5201c4acb20

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/87908d8d-031b-4595-ba6f-37d5560a816c

**Comment by akshay8551** [comment]
Android -



https://github.com/user-attachments/assets/73680da9-322c-4b70-be3e-1df53d2d554d

**Comment by Deveshshankar** [comment]
https://github.com/bithyve/bitcoin-tribe/issues/594 Duplicate closing this
