### ISSUE TITLE
Setting up Supported Mode animation 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#586]
- [x] Need to add bottom text and animation at bottom

<img width="304" alt="Screenshot 2024-11-26 at 2 44 19 PM" src="https://github.com/user-attachments/assets/7264f2c1-1478-4b35-8fd5-4032a211ffe0">

**Comment by Jddesigner0003** [comment]
@akshay8551   Please check attached JASON file 
[Bitcoin Structure.json](https://github.com/user-attachments/files/17929928/Bitcoin.Structure.json)

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/b1b24fad-4228-42dd-830a-aafb231ae9ff






https://github.com/user-attachments/assets/18abe5e6-bf3f-4782-979a-8d9b75baa5eb

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/d12f5a1e-957e-412e-8533-00427fc8cdf8

**Comment by Deveshshankar** [comment]
Completed
