### ISSUE TITLE
Backup & Recovery options 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#588]
- [ ] For Tribe RGB backup is to be done for Seed Phrase and RGB assets

SelfCustody > On Chain  Seed Phrase to be backup by the user outside the app.
RGB Assets will be backed by relay server by default.  At any moment user can download this file on his phone. While **recovery** user can provide this RGB file if we do not find it on relay.

SelfCustody > On Chain & Lightning  **No Backup**

Supported  Only Seed Phrase to be backup by the user outside the app.

- [ ] 3.Supported Wallet

Task: Simplify the backup process for supported wallets.
Backup Option:
Seed Words Only: Ensure seed words are the only recovery method, focusing on simplicity and ease of use.

Recovery Options Tasks

**1. Recovery Options for Self-Custody On-Chain Wallet**

Task: Implement two recovery options for on-chain wallets:
Seed Option: Allow users to recover their wallet using their seed words.
RGB asset Backup Option: Provide recovery through stored asset backup on relay.

**2. Recovery Options for Self-Custody Lightning Wallet*

Node Details Option: Include recovery through node details for users with node setups.
UI/UX Enhancements:
Display the recovery options with clear instructions and relevant tooltips.

**3. Recovery Options for Supported Wallet**

Task: Limit recovery for supported wallets to seed words only.
No node details are required for supported wallets.

1. Supported Wallet Recovery Process (error case )

Scenario:
If the supported node is not found from the relay, or no metadata/RGB file is available, prompt the user with two fallback options:
Upload a Zip File Manually: Allow the user to upload a previously saved zip file for recovery.
Create a New Wallet: Provide an option to create a new wallet if no backup is available.

**Comment by Jddesigner0003** [comment]
https://us02web.zoom.us/rec/share/7HRkrivYTJdKOkYzaKIU94kyruO7dliSzPuClXAWMYTdyMSwpDpRaRMF6EFa8dYs.Rec-FOosgwpNZkIk
Passcode: FC#N7*VC

**Comment by Deveshshankar** [comment]
@Jddesigner0003 We are doing Backup part in 41

**Comment by Jddesigner0003** [comment]
@Deveshshankar   Hey I was designed the backup options can you please first review from your side and share with me feedback after that will share with team for final preview 

https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=4475-44912&t=0SyqMylwcCT0qgVU-1

**Comment by Jddesigner0003** [comment]
@Deveshshankar @cakesoft-shashank   Please check the updated backup flow. The subtitle content is pending, and I will update it in the design once the team member sends it to me.

Figma: https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=4615-50042&t=Jl4PC3HnGo4lFrBD-1

<img width="6810" alt="Self-Custody On-Chain Backup (1)" src="https://github.com/user-attachments/assets/5075f958-4a97-4f78-8796-a4d3775b5b11">

**Comment by Deveshshankar** [comment]
https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=4475-44912&m=dev&t=2DNw3fzzWNwIsbYT-1 @cakesoft-shashank updated approved flow Backup and Recovery

**Comment by Deveshshankar** [comment]
Umbrella issue so closing
