### ISSUE TITLE
Getting error on creating collectibles in android 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#590]
![1000180762_720](https://github.com/user-attachments/assets/6e2ac9f5-ae0b-438a-8f3b-dafef30ed73b)

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/b13c6e67-de12-42cb-9b1d-c72d4096a06f

**Comment by akshay8551** [comment]
Lightning (Node) - 



https://github.com/user-attachments/assets/a8f27b59-2cf0-4423-9b81-200dcc98553d

**Comment by akshay8551** [comment]
OnChain -




https://github.com/user-attachments/assets/e0ae77b9-a018-499b-ad68-9edfd1e39e71

**Comment by Deveshshankar** [comment]
Completed works fine
