### ISSUE TITLE
Error on supported mode 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#596]
Getting this error tried after 60 min still same error 
![img_14c34464b970-1_720](https://github.com/user-attachments/assets/c77893f3-8460-4650-af3b-d83d7bc34720)

**Comment by Deveshshankar** [comment]
Completed in build number 0.2.5 (63)

**Comment by cakesoft-shashank** [comment]
This is irrelevant now

**Comment by Deveshshankar** [comment]
Completed
