### ISSUE TITLE
Need to update latest screen in Website

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#600]
- [x] Wallet detail screen 
- [x] Other changes made in 41 and 42
- [x] Need to add few more screens based on new design 
- [x] @Jddesigner0003 Will need screen for web

**Comment by Jddesigner0003** [comment]
@Deveshshankar  

1.  Wallet detail screen

** Utkarsh sir comment "Create Wallet > The button should be intuitive enough to show collapse and expand." **

-> Based on the comment, I replaced the arrow with a wallet icon, as it better represents the wallet selection. Additionally, I incorporated up and down arrows within the wallet icon to indicate the collapse and expand functionality.

[Figma Link](https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=5001-14724&t=Biv2TrXJ9XJIx6Zc-1)

![image](https://github.com/user-attachments/assets/175c94bc-2176-4e73-90eb-4850f2429496)

**Comment by Jddesigner0003** [comment]
@Deveshshankar  

All image added in this zip file can you please check and let me know if you need anything else 

Even is added in figma you can check there as well.

[Figma Link](https://www.figma.com/design/e0RxSAiRCMt5Z48LJVNEXr/Tribe-RGB?node-id=2177-6856&t=Biv2TrXJ9XJIx6Zc-1)

[Website IMG.zip](https://github.com/user-attachments/files/18241125/Website.IMG.zip)

**Comment by Deveshshankar** [comment]
https://bitcointribe.app/ updated as per latest changes
