### ISSUE TITLE
Update in Design File

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#608]
- [ ] For Bitcoin and Lightening Send- The transaction has been broadcasted successfully

![screenshot_2024-12-05_at_2 35 17___pm_720](https://github.com/user-attachments/assets/d7b6108b-d87d-4275-8714-ee78aa227ee3)

- [ ] For Asset Send: The Asset has been broadcasted successfully

**Comment by Jddesigner0003** [comment]
@Deveshshankar   I was changed all in all the screen and by change any if you see in figma anytime, you can comment there i will change it

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/1f0ef668-fda2-4c7e-bfab-a519d9f66257

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/6359242e-e0d2-4cad-bb1e-4ba2af671cd0

**Comment by Deveshshankar** [comment]
Completed
