### ISSUE TITLE
Backup is done but it doesn't indicate on Backup screen 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#612]
User has done the backup but but it doesn't indicate on Backup screen  cc @akshay8551 

https://github.com/user-attachments/assets/8dfc10cb-32e9-4450-b020-45d5f9e7f59f

**Comment by akshay8551** [comment]
<img width="335" alt="Screenshot 2024-12-10 at 3 23 57 PM" src="https://github.com/user-attachments/assets/c7bae6d7-e012-4ef7-b05c-9410353c74c0">

**Comment by akshay8551** [comment]
![simulator_screenshot_C4FF1611-8E86-4DB6-B924-07FDB660ABBF](https://github.com/user-attachments/assets/f17f8b19-cc9d-47cc-84d5-f1671992d32f)

**Comment by Deveshshankar** [comment]
Can't see on latest

**Comment by Deveshshankar** [comment]
Completed in version 0.2.5 (65)
