### ISSUE TITLE
Content improvement on this screen 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#614]
- [ ] Need to verify content on this screen 

![img_9747_720](https://github.com/user-attachments/assets/39bc6062-a90e-4d73-8eba-5963d026d2a5)
![img_9743_720](https://github.com/user-attachments/assets/ce5c3d9c-ca76-4393-890e-d17cdf0b68fa)
![img_9745_720](https://github.com/user-attachments/assets/abbd160e-0d8c-4fb5-8bcf-3e71e536fe1a)
![img_9747_720](https://github.com/user-attachments/assets/4e742e5a-1987-4ec5-a295-e1cb83a45b47)

**Comment by akshay8551** [comment]
![simulator_screenshot_9C41FF53-DAF7-4C22-8A96-33717EEB6848](https://github.com/user-attachments/assets/f568e163-aedf-4226-956c-0ebe891acda0)

**Comment by akshay8551** [comment]
![simulator_screenshot_A0DB0B09-8464-4704-A811-F0736302B9B9](https://github.com/user-attachments/assets/73674687-1a60-4af3-b1b9-ec5cce85fdd8)

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/14b7fc74-8538-4eb6-9274-7ea440f9fed7

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/e333b0ab-688c-4b74-aed6-cba5393d021e

**Comment by Deveshshankar** [comment]
Completed
