### ISSUE TITLE
App logo in iOS is not correct 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#619]
![IMG_9796](https://github.com/user-attachments/assets/e090e353-ddf2-418b-85d2-3c79587fd9b4)

**Comment by akshay8551** [comment]
![simulator_screenshot_3D863164-A3D3-4B70-BF0E-D74F7CB2EF39](https://github.com/user-attachments/assets/c72cdbe1-c1c3-4420-90ac-2c96a703b79f)

**Comment by akshay8551** [comment]
![IMG_F83A35899202-1](https://github.com/user-attachments/assets/b238c00e-fdca-4478-800a-1d3930ec96a5)

**Comment by Deveshshankar** [comment]
Completed
