### ISSUE TITLE
Transaction refresh behaviour is not correct 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#620]
@akshay8551 We resolved why it is coming again
![IMG_9789](https://github.com/user-attachments/assets/98b9f756-e4bc-4dee-9267-2eb9e4f4a86d)

**Comment by akshay8551** [comment]
@Deveshshankar ,

This is not bug. There was bug, where empty space appeared while refresh transaction list and also that time not appeared loader (loading animation). 

Thanks

**Comment by Deveshshankar** [comment]
Completed
