### ISSUE TITLE
Ui bugs in onboarding screen 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#621]
@akshay8551 it looks blank not as per dark mode if design is not available please ask and create a issue 
![1000184623_720](https://github.com/user-attachments/assets/468a6bc5-e562-4895-bcbb-3561bd02acfb)

**Comment by akshay8551** [comment]
![simulator_screenshot_D60E3AA9-EDC0-4631-802C-ED9690E4D75E](https://github.com/user-attachments/assets/a3c67c94-42c6-4316-beb2-fdf647d826d2)

**Comment by Deveshshankar** [comment]
Completed
