### ISSUE TITLE
Unable to get this (Confirm Backup )

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#622]
@akshay8551 What is user should enter here ? 
![IMG_9794](https://github.com/user-attachments/assets/00140ff1-7f2d-43e7-97eb-90ec5a080213)

**Comment by akshay8551** [comment]
![simulator_screenshot_17C4C5DA-CDF4-4878-BADA-944473061F0E](https://github.com/user-attachments/assets/b4a56527-8f63-4df1-9dbe-5a4c4d91408b)


![simulator_screenshot_64A2583B-2A09-487B-9CC8-5B309D3C1961](https://github.com/user-attachments/assets/7fd3edd1-ece2-4ceb-8cb0-83498186943a)

**Comment by akshay8551** [comment]
<img width="339" alt="Screenshot 2024-12-10 at 11 04 52 AM" src="https://github.com/user-attachments/assets/9e6dd0ea-1d2b-4e3b-8dc8-298cb4a9d268">

**Comment by akshay8551** [comment]
<img width="335" alt="Screenshot 2024-12-10 at 11 10 30 AM" src="https://github.com/user-attachments/assets/c16c0220-3c7e-4bed-a40a-ec5b8c72e03d">

<img width="335" alt="Screenshot 2024-12-10 at 11 10 54 AM" src="https://github.com/user-attachments/assets/3f685dec-d451-4036-8370-713cc16926c7">

**Comment by Deveshshankar** [comment]
Completed
