### ISSUE TITLE
Bug in iOS 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#623]
Getting errors
- [ ] In Creating app ((supported mode )
- [ ] Trying to recover wallet (seed words )

![IMG_6717 2](https://github.com/user-attachments/assets/b7a52408-4b60-4f83-b391-00c7b58fa870)
![IMG_6714 3](https://github.com/user-attachments/assets/9b4da806-fb9d-4390-87c3-52195f5036bf)

**Comment by cakesoft-shashank** [comment]
Env missmatch issue

**Comment by Deveshshankar** [comment]
Completed
