### ISSUE TITLE
First asset creation (User experience is not correct )

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#624]
@akshay8551 So when user creates asset coins or collectibles loader stops for a while and again starts this is not correct behaviour it should run until process is completed pause and play behaviour is not correct 

To Reproduce :  create fresh app > get sats > and start creating a new coins or collectibles > Now you can see the loader animation behaviour

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/9b08eb5c-7bd2-41d0-8ca2-81137124e510

**Comment by Deveshshankar** [comment]
Completed
