### ISSUE TITLE
Asset creation improvement 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#629]
Uploading ScreenRecording_12-09-2024 12-48-58_1.MP4…

- [ ] The collectible name on the home screen is not visible fully.
- [ ] The Coin Ticker should be the first priority to show than the name
- [x] #634

**Comment by Jddesigner0003** [comment]
@Deveshshankar   After new UI this will be fix

**Comment by Deveshshankar** [comment]
Closing since we are changing the new UI
