### ISSUE TITLE
There should be check on onchain wallet Backup 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#633]
As per discussion  @cakesoft-shashank  ensure that users cannot proceed to Step 2 (Asset Backup) without completing Step 1 (Wallet Backup). A validation check needs to be implemented to enforce this flow.

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/2c071971-439e-4611-9060-e1b0ec1c7df9

**Comment by Deveshshankar** [comment]
Completed and verified in Version 0.2.5 (65)
