### ISSUE TITLE
After Asset creation it takes time to display on Home Screen

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#634]
- [ ] After Asset creation it takes time to display on Home Screen 

- [ ] @akshay8551 It also take time when we recover

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/94f496d5-d8f7-4454-ae92-069cefec7b8d

**Comment by akshay8551** [comment]
https://github.com/user-attachments/assets/23b57b11-1c08-4392-8889-d9096cb740e6

**Comment by Deveshshankar** [comment]
Completed and verified in Version 0.2.5 (65)
