### ISSUE TITLE
Error on creating Asset 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcoin-tribe#642]
- [ ] On adding maximum value it shows error toast but also it allows to create asset @akshay8551 Logic missing ideally it should not 

- [ ] Check on both coins and collectibles 

- [ ] Also created asset does not appears on home 

https://github.com/user-attachments/assets/b61e7562-b10b-4071-9eee-53ac2b6d7ff6

**Comment by akshay8551** [comment]
@Deveshshankar , 

We check maximum value while user enter amount in input box. We're not allow to enter greater than max value. You can rethink about this issue if anything need to add/improve please let me know.

Thanks

**Comment by Deveshshankar** [comment]
Closing this for now if it will be reported by more people will close
